# Generated by Django 5.1.7 on 2025-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
    ]
