# Generated by Django 5.1.7 on 2025-03-15 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timing', models.CharField(choices=[('08:00-12:00', '08:00 AM - 12:00 PM'), ('12:00-16:00', '12:00 PM - 04:00 PM'), ('16:00-20:00', '04:00 PM - 08:00 PM'), ('24/7', 'Available 24/7')], max_length=20)),
                ('appointment_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('specialities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.specialities')),
            ],
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
