# Generated by Django 5.1.7 on 2025-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_delete_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
