# Generated by Django 5.1.7 on 2025-03-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_bookappoinment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialities',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Pediatrician', 'Pediatrician'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Gynecologist/Obstetrician', 'Gynecologist/Obstetrician'), ('Dermatologist', 'Dermatologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Psychiatrist', 'Psychiatrist'), ('General Surgeon', 'General Surgeon')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Specialities',
        ),
    ]
