# Generated by Django 5.1.7 on 2025-03-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
