# Generated by Django 5.1.7 on 2025-03-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
